### ISSUE TITLE
After task completion variables are not set with newer version

### ISSUE THREAD

**Issue by praba984** [yrtimiD/azure-pipelines-semver-bump#1]
After task completion variables are not set with the newer version. If I rerun newly then it starts from the default number

**Comment by yrtimiD** [comment]
Can you, please, share the execution log? Please set variable system.debug to true before run.

**Comment by yrtimiD** [comment]
BTW, task is only updates variable locally. Its value is not preserved for next build (it can be done by committing file with last version, but it's out of scope of this specific task)

**Comment by yrtimiD** [comment]
Closing because of missing details.
