### ISSUE TITLE
 Does not increase version

### ISSUE THREAD

**Issue by xsavron** [yrtimiD/azure-pipelines-semver-bump#3]
Good day! I use it in TFS, the problem is that it does not increase the version, I attach the logs.
[logs_2219.zip](https://github.com/yrtimiD/azure-pipelines-semver-bump/files/5142229/logs_2219.zip)

**Comment by yrtimiD** [comment]
Hi,
from logs I see that it does:
```
020-08-28T13:02:54.1086278Z ##[section]Запускается: Semver bump patch ApplicationVersion
2020-08-28T13:02:54.1230146Z ==============================================================================
2020-08-28T13:02:54.1230417Z Task         : Semver version bump
2020-08-28T13:02:54.1230640Z Description  : Bumps (increments) semantic version
2020-08-28T13:02:54.1230836Z Version      : 1.0.0
2020-08-28T13:02:54.1230997Z Author       : Dmitry Gurovich
2020-08-28T13:02:54.1231152Z Help         : 
2020-08-28T13:02:54.1231370Z ==============================================================================
2020-08-28T13:02:54.3780226Z Current version value is "2.0.38"
2020-08-28T13:02:54.3780467Z Bumping patch version
2020-08-28T13:02:54.3780827Z New version is 2.0.39
2020-08-28T13:02:54.3803361Z ##[section]Завершается: Semver bump patch ApplicationVersion
```

All this means that before task execution value of your "ApplicationVersion" variable was "2.0.38" and after task it should become "2.0.39". If you want to ensure it - just add a task which will print the value of $(ApplicationVersion).

If you don't see that version is changed, please rerun your build with variable `System.Debug` set to true, this will enable verbose logging.

**Comment by seraphx2** [comment]
I think you misunderstand him. It does increase the version, but it does not save it back to the variable as the description of the task says it will. This task is entirely useless unless the variable is updated (and yes, I have "Settable at queue time" checked). It remains the original value I put in there.

**Comment by seraphx2** [comment]
```
##[debug]Evaluating condition for step: 'Semver bump patch api-semver'
##[debug]Evaluating: succeeded()
##[debug]Evaluating succeeded:
##[debug]=> True
##[debug]Result: True
Starting: Semver bump patch api-semver
==============================================================================
Task         : Semver version bump
Description  : Bumps (increments) semantic version
Version      : 1.0.0
Author       : Dmitry Gurovich
Help         : 
==============================================================================
##[debug]Using node path: /home/vsts/agents/2.175.2/externals/node/bin/node
##[debug]agent.TempDirectory=/home/vsts/work/_temp
##[debug]loading inputs and endpoints
##[debug]loading INPUT_VERSIONVARIABLE
##[debug]loading INPUT_INCREMENTLEVEL
##[debug]loading INPUT_PREID
##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
##[debug]loaded 6
##[debug]Agent.ProxyUrl=undefined
##[debug]Agent.CAInfo=undefined
##[debug]Agent.ClientCert=undefined
##[debug]Agent.SkipCertValidation=undefined
##[debug]VersionVariable=api-semver
##[debug]IncrementLevel=patch
##[debug]PreId=rc
##[debug]api-semver=1.0.58
##[debug]Using variable "api-semver"
##[debug]Increment level is "patch" with preId "rc"
Current version value is "1.0.58"
Bumping patch version
New version is 1.0.59
##[debug]set api-semver=1.0.59
##[debug]Processed: ##vso[task.setvariable variable=api-semver;issecret=false;]1.0.59
##[debug]task result: Succeeded
##[debug]Processed: ##vso[task.complete result=Succeeded;]New version "1.0.59" was saved back to "api-semver" variable
Finishing: Semver bump patch api-semver
```

It says it's successful, but each time I run it, it starts over at 1.0.58 and the variable value is unchanged in the Variables section.

**Comment by yrtimiD** [comment]
@seraphx2 The TFS variables are not persisted between builds and that's by-design. You should do extra steps for saving "last" version after increment and to load it on next build. The task only updates value of the variable for **current** build, so, in the next steps you can pass it anywhere you want and preserve it using any technics you like. I personally saved it into file (version.txt or package.json) and actively committed it back to tfs during the build. There are plenty of other ways you can choose.

**Comment by seraphx2** [comment]
Then you really need to change the description of your marketplace (and README) which explicitly says this task will update the original variable for you: "Version value is **read from the configured environment variable**, incremented accordingly and **written back to the same variable**."

**Comment by yrtimiD** [comment]
@seraphx2 , well, you should know how TFS works. During the build you have a bunch of variables which have initial value defined in the build definition. I DO update its value during the build, and variable will keep its value until the very end of run. You can check this by echoing it step after. I'll add a note to readme that variables values are not preserved between builds, but this should be obvious for tfs users.

**Comment by seraphx2** [comment]
Yeah. I changed my response a little bit. Haha. I do get that part I guess. But it *is* a little misleading. I don't work in this constantly, so that part slipped my mind about how things persist. But total noobs will not necessarily know that at all, and the description as-is would be confusing and set wrong expectations.

**Comment by seraphx2** [comment]
I am curious though. Is it impossible for tasks to update variables permanently or do you just want to leave that up to the user?

**Comment by yrtimiD** [comment]
Sadly, that's how azure pipelines works and version incrementing is a real PITA for everybody. There is no such thing as a "persisted variable". This task solves only one issue at a time. Getting the previous version and saving incremented must be done separately. There is no "drag'n'drop" solution for this.
On my job I was required to reinvent the wheel and create kind of 3-4 different tasks only to accomplish this :(
